import { NextPage } from "next";
import { Scrollbars } from "react-custom-scrollbars-2";
import Head from "next/head";
import { useMediaQuery } from "react-responsive";
import { motion } from "framer-motion";

const Experience: NextPage = () => {
  const isTabletOrMobile = useMediaQuery({ query: "(max-width: 943px)" });

  const experiences = [
    {
      company: "Bluestock",
      role: "Software Development Engineer (SDE) Intern & Team Co-Lead",
      period: "March 2025 – June 2025",
      achievements: [
        "Co-led development of a production-grade IPO web application and RESTful API, enabling real-time IPO data delivery across internal and client platforms.",
        "Engineered a scalable backend using Django and a responsive frontend with HTML, CSS, JavaScript, and Bootstrap 5, prioritizing performance and user experience.",
        "Employed Agile methodologies, leveraging Git/GitHub for version control and team collaboration, Postman for API validation, and ChatGPT for accelerated debugging and database schema design."
      ],
      tech: ["Javascript", "Django", "RESTful APIs", "Bootstrap 5", "Agile", "Git/GitHub", "Postman"]
    },
    {
      company: "Aligner",
      role: "SDE Freelancer",
      period: "June 2024 – May 2025",
      achievements: [
        "Projects with OpenAI-style LLMs (e.g., ChatGPT, Gemini)",
        "Worked on 10+ advanced projects focused on improving large language models (LLMs) through Reinforcement Learning from Human Feedback (RLHF), with a strong emphasis on code generation, correction, and quality enhancement.",
        "Validated and optimized model-generated code in Java, C++, Python, and JavaScript, ensuring clean architecture, optimal performance, and adherence to modern software engineering best practices.",
        "Contributed to prompt engineering, edge-case handling, and response evaluation, driving improvements in model accuracy, instruction-following capability, and contextual reasoning for technical tasks."
      ],
      tech: ["Java", "C++", "Python", "LLMs", "RLHF", "JavaScript", "Prompt Engineering"]
    },
    {
      company: "Outlier",
      role: "SDE Freelancer",
      period: "September 2024 – March 2025",
      achievements: [
        "Contributed to 4 high-impact projects focused on improving AI-generated code and model responses through systematic evaluation and optimization.",
        "Reviewed and corrected code in C++ and Python, enhancing logic, fixing bugs, and ensuring alignment with performance, scalability, and readability standards.",
        "Specialized in code optimization, performance tuning, and response refinement, improving the accuracy and clarity of technical outputs generated by large language models.",
        "Collaborated in iterative review cycles, performing prompt engineering, edge-case validation, and quality assurance to strengthen model consistency and reliability."
      ],
      tech: ["C++", "Python", "Code Optimization", "LLMs", "Prompt Engineering", "Quality Assurance"]
    }
  ];

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2
      }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        duration: 0.5
      }
    }
  };

  return (
    <Scrollbars
      autoHide
      autoHideTimeout={1000}
      autoHideDuration={200}
      universal={true}
    >
      <Head>
        <title>Experience - Shivam Tiwari</title>
        <meta
          name="description"
          content="Professional experience and work history of Shivam Tiwari"
        />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:title" content="Experience - Shivam Tiwari" />
        <meta
          name="description"
          content="Professional experience and work history of Shivam Tiwari"
        />
        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Shivam Tiwari" />
        <meta property="og:image" content="/mainthumbnail.PNG" />
        <meta property="og:image:width" content="1040" />
        <meta property="og:image:height" content="600" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="HandheldFriendly" content="True" />
        <meta name="MobileOptimized" content="320" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="twitter:widgets:csp" content="on" />
      </Head>
      <div className="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <h2 className="text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-indigo-500 to-purple-500 mb-4">
              Experience
            </h2>
            <p className="text-xl text-gray-400 max-w-2xl mx-auto">
              My professional journey and work history, showcasing my growth and expertise in software development.
            </p>
          </motion.div>

          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="space-y-8"
          >
            {experiences.map((exp, index) => (
              <motion.div
                key={index}
                variants={itemVariants}
                className={`relative ${!isTabletOrMobile ? "pl-8" : "pl-4"}`}
              >
                {!isTabletOrMobile && (
                  <div className="absolute left-0 top-0 w-4 h-4 rounded-full bg-gradient-to-r from-indigo-500 to-purple-500 transform hover:scale-125 transition-transform duration-300"></div>
                )}
                <div className="bg-gray-800/50 backdrop-blur-sm rounded-xl p-10 shadow-2xl hover:shadow-xl hover:shadow-purple-500/50 transition-all duration-300 border border-gray-700/50">
                  <div className="flex flex-col md:flex-row md:justify-between md:items-start mb-6">
                    <div>
                      <h3 className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400 mb-2">
                        {exp.company}
                      </h3>
                      <p className="text-indigo-300 font-medium text-lg">{exp.role}</p>
                    </div>
                    <p className="text-gray-400 mt-2 md:mt-0 text-lg font-medium">{exp.period}</p>
                  </div>
                  <ul className="space-y-4 mb-6 list-disc pl-5">
                    {exp.achievements.map((achievement, i) => (
                      <motion.li
                        key={i}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.1 }}
                        className="text-gray-300 text-lg leading-relaxed"
                      >
                        {achievement}
                      </motion.li>
                    ))}
                  </ul>
                  <div className="flex flex-wrap gap-3">
                    {exp.tech.map((tech, i) => (
                      <motion.span
                        key={i}
                        initial={{ opacity: 0, scale: 0.8 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: i * 0.1 }}
                        className="px-4 py-2 text-sm font-medium text-indigo-400 bg-indigo-900/30 rounded-full border border-indigo-500/30 hover:bg-indigo-900/50 transition-colors duration-300"
                      >
                        {tech}
                      </motion.span>
                    ))}
                  </div>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </div>
    </Scrollbars>
  );
};

export default Experience; 